# Generated by Django 5.1.7 on 2025-03-14 04:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Server Name')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='Hostname')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=20, verbose_name='Status')),
                ('server_type', models.CharField(choices=[('web', 'Web Server'), ('db', 'Database'), ('cache', 'Cache'), ('app', 'Application Server'), ('other', 'Other')], default='other', max_length=50, verbose_name='Server Type')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='CPU Usage (%)')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='Memory Usage (%)')),
                ('disk_usage', models.FloatField(default=0.0, verbose_name='Disk Usage (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(verbose_name='CPU Usage (%)')),
                ('memory_usage', models.FloatField(verbose_name='Memory Usage (%)')),
                ('disk_usage', models.FloatField(verbose_name='Disk Usage (%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.server')),
            ],
            options={
                'verbose_name_plural': 'Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=20, verbose_name='Status')),
                ('port', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Port Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.server')),
            ],
        ),
    ]
